pretrained_base_model_path: "./pretrained_weights/stable-diffusion-v1-5/"
pretrained_vae_path: "./pretrained_weights/sd-vae-ft-mse"
image_encoder_path: "./pretrained_weights/image_encoder"
denoising_unet_path: "./pretrained_weights/denoising_unet-54400.pth"
reference_unet_path: "./pretrained_weights/reference_unet-54400.pth"

inference_config: "./configs/inference/inference_genshin_image.yaml"
weight_dtype: 'fp16'

input_video_path: "./test_video/Shuishen.mp4"