pretrained_base_model_path: "./pretrained_weights/stable-diffusion-v1-5/"
pretrained_vae_path: "./pretrained_weights/sd-vae-ft-mse"
image_encoder_path: "./pretrained_weights/image_encoder"
denoising_unet_path: "./exp_output/gensin_stage1/denoising_unet-60000.pth"
reference_unet_path: "./exp_output/gensin_stage1/reference_unet-60000.pth"

inference_config: "./configs/inference/inference_gensin.yaml"
weight_dtype: 'fp16'

input_video_path: "/data2/zjx/dataset/gensin_pv/test_video/Naweiya.mp4"